server:
  port: 8090

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin

graphiql:
  enabled: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true